public class CompletionFindException2 {
	void foo() throws Ex {
	}
}